### ISSUE TITLE
Some issue with spaces when text alignment is set to Left or Center

### ISSUE THREAD

**Issue by Walter-Correa** [BitSain/ZTDEditor-SAMP#2]
I'm using a project from the old Zamaroth editor.
If the text is aligned to the left or center and there is some space in the text, a line break occurs, as you can see in the images:

**Left aligned without spaces:**
![Screenshot_64](https://github.com/BitSain/ZTDEditor-SAMP/assets/20175176/c4e0a667-ff15-424f-bb90-31bb58a1d40c)

**Left aligned with space:**
![Screenshot_65](https://github.com/BitSain/ZTDEditor-SAMP/assets/20175176/f832b160-47a3-4541-abc8-33e0ec1bb4b3)

**Right aligned with space:**
![Screenshot_66](https://github.com/BitSain/ZTDEditor-SAMP/assets/20175176/822323d5-a85f-4605-b887-4f4645ceb2e8)

**Left aligned without spaces:**
![Screenshot_67](https://github.com/BitSain/ZTDEditor-SAMP/assets/20175176/31d8f8f0-9f25-42b1-8635-163dc612f2e9)

**Comment by BitSain** [comment]
Replace the space with the character: _
I will automate this in the next update.
